service: backend

provider:
  name: aws
  stackName: backend-serverless
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

# functions are defined in here
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: api/example/hello
          cors: true

  name:
    handler: handler.name
    events:
      - http:
          method: get
          path: api/example/name
          cors: true

# webpack configuration
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - 'aws-sdk'

# plugins that Serverless framework is using
plugins:
  - serverless-webpack
  - serverless-offline
